sudo: required

services:
  - docker

before_install:
  - docker build -t willyddn/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true willyddn/react-test npm test

after_success:
  - docker build -t willyddn/multi-client ./client
  - docker build -t willyddn/multi-nginx ./nginx
  - docker build -t willyddn/multi-server ./server
  - docker build -t willyddn/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push willyddn/multi-client
  - docker push willyddn/multi-nginx
  - docker push willyddn/multi-server
  - docker push willyddn/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-west-3
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-west-3-390848313631
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"
    
